version: '3'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && exec gunicorn deploy_app.wsgi:application -b 0.0.0.0:8000 --reload
      "
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - db
      - backend
    ports:
      - 80:80
    volumes:
      - ./static/:/static
volumes:
  postgres_data: