version: '3.7'

services:
  backend:
    build: ./
    restart: always
    command: bash entrypoint.sh
    volumes:
      - ./:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.1
    # priveleged and restart is required?
    restart: always
    volumes:
      - deploy_app_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432
  nginx:
    build: ./nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - backend
volumes:
  deploy_app_postgres_data: